model:
  provider: "zhipu"
  name: "glm-4.6v"
  base_url: "https://open.bigmodel.cn/api/paas/v4/"
  api_key: "5fdb0d4bbbb24692b15469a73ad23ac1.DWeb93wnlCVcrwyx"
  temperature: 0.01
  thinking: true

server:
  host: "127.0.0.1"
  port: 19000
